### ISSUE TITLE
Optional message encryption and push message examples

### ISSUE THREAD

**Issue by costinm** [webpush-wg/webpush-protocol#106]
"The ciphertext of the push message is included in the body of the request."
1. The example looks like base64 - it should be clear it's binary content ( ciphertext is not base64)
2. If we give an example with ciphertext, it should include the extra headers. 

Alternative is to say "The content of the push message is included", and have a "I am walrus" example" - 
with a link to the encryption document for proper encrypted example. But since most implementations
will require encryption - I think it's better to add the extra headers and make it clear it's binary.

**Comment by brianraymor** [comment]
I prefer the "Alternative" approach to keep the webpush examples simple and uncluttered. I will add a reference to the example in  [vapid](https://tools.ietf.org/html/draft-ietf-webpush-vapid-00#section-2.2) to illustrate encryption.
