### ISSUE TITLE
Delivery receipt may be sent before AS request delivery

### ISSUE THREAD

**Issue by idelpivnitskiy** [webpush-wg/webpush-protocol#115]
Here may be a problem with push messages with a little value of TTL. Message may be sent to a UA and ack may be received from the UA before the AS will send a HTTP GET request to the receipt subscription resource. PS will retry delivering of receipt, but TTL may expire before this.

To eliminate this problem it would be better to introduce separate resource for an AS: something like `/subscribe` for a UA, where AS may create a receipt subscription.
Benefits:
- subscription may be created and receiving Push Message Receipts may be requested before sending a new push message => no delivery receipts will be lost;
- no need to send a push message to get receipt subscription resource;
- easy receipt subscription management and receiving receipts (AS may have a separate thread or service for this purpose);
- simplifying registration of a new push message on PS side: just one new object will be created (a push message), no need to think about management of receipt subscriptions (what it needs to do? return the same receipt subscription or a new one).

**Comment by brianraymor** [comment]
@idelpivnitskiy - Regarding _introduce separate resource for an AS: something like  /subscribe  for a UA, where AS may create a receipt subscription._ 

that was the original design. We recently simplified the design in -05 after reaching consensus following the [presentation](https://www.ietf.org/proceedings/95/slides/slides-95-webpush-1.pdf) after IETF95. 

@martinthomson noted the risk at that time - http://www.ietf.org/mail-archive/web/webpush/current/msg00456.html

**Comment by idelpivnitskiy** [comment]
@brianraymor thanks for the information. Moved discussion to the mailing list

**Comment by brianraymor** [comment]
@martinthomson elaborated further on the [mailing list](http://www.ietf.org/mail-archive/web/webpush/current/msg00599.html):

_The only good solution to this general problem is to have a longer TTL._

_Even if you fix the "bug" you identified, a short TTL can expire between the time that the message is delivered to the user agent and before the acknowledgment can reach the push service._
