### ISSUE TITLE
URIs and resources

### ISSUE THREAD

**Issue by martinthomson** [webpush-wg/webpush-protocol#14]
Let's be consistent about how we talk about the things:

> At some point, we need to be consistent about how we reference subscription, push, and push message
> 1. Is it push or "push"?
> 2. Is it push URI or push resource?

There I think that we might want to settle on no scare quotes and to use "push resource" consistently for the thing, and "push resource URI" for the label that appears in the protocol.

**Comment by brianraymor** [comment]
Consider using the link relation name:
1. push:message;subscription
2. push:message

etc.

**Comment by brianraymor** [comment]
Editorial pass was completed.
