### ISSUE TITLE
SOP

### ISSUE THREAD

**Issue by martinthomson** [webpush-wg/webpush-protocol#142]
From Stephen:

> (*) I assume you do not want to add something, but
> if you did, then my suggestion would be along the
> lines of "Applications using this push mechanism
> are likely to need additional security mechanisms
> to produce an overall useful system, e.g. when the
> UA is a browser, then the SOP needs to be enforced,
> which can be achieved via [refs]. Other applications
> using this mechanism may require similar kinds of
> higher level security mechanism over and above
> what is defined here."

**Comment by brianraymor** [comment]
Is this already addressed by https://tools.ietf.org/html/draft-ietf-webpush-protocol-11#section-8

   _Applications using this protocol MUST use mechanisms that provide
   confidentiality, integrity and data origin authentication.  The
   application server sending the push message and the application on
   the user agent that receives it are frequently just different
   instances of the same application, so no standardized protocol is
   needed to establish a proper security context._

**Comment by martinthomson** [comment]
OBE.
