### ISSUE TITLE
Add maximum TTL

### ISSUE THREAD

**Issue by martinthomson** [webpush-wg/webpush-protocol#2]
It was less clear that this was needed than #1 was, but the idea is that it would be good for a user agent (or maybe an application server too) to be able to learn the maximum TTL that a push service was willing to maintain.

**Comment by martinthomson** [comment]
Discussed today: conclusion was to have subscriptions expire if the server is unwilling to maintain them over a long period of inactivity.

**Comment by DanDruta** [comment]
It should be fine if we let subscriptions expire if the server is unwilling to maintain them over a long period of inactivity.

**Comment by brianraymor** [comment]
There is a related failure case in the current draft related to acknowledgements:

_The push server MUST push a response with a status code of 5XX (TBD)
   if the user agent fails to acknowledge the receipt of the push
   message or the push server fails to deliver the message prior to its
   expiration._

**Comment by brianraymor** [comment]
Discussed. Discovery of maximum TTL is not required at this time.
