### ISSUE TITLE
Delete immediately after TTL expires?

### ISSUE THREAD

**Issue by martinthomson** [webpush-wg/webpush-protocol#35]
@benbangert notes that the requirement to delete immediately after TTL expires (or at least soon after) is not compatible with certain push service implementation strategies.  We should allow for these designs.

Since the data is encrypted, the implications of retention are less, but we should probably still require some upper bound on this time.

**Comment by brianraymor** [comment]
As [suggested](https://mailarchive.ietf.org/arch/msg/webpush/uI_-MFgaFHooHR9B2m0xf025hoQ) by @costinm:

_the spec should certainly require that expired messages are not delivered, but not how it is implemented. Best time bound would be 'maximum TTL' - it's  cheapest in some databases._
