### ISSUE TITLE
Port numbers

### ISSUE THREAD

**Issue by martinthomson** [webpush-wg/webpush-protocol#37]
Different ports have different timeouts and 443 isn't necessarily the best choice.  Some network operators bless the ports that existing services use.

However, 5223 and 5228 are already registered with IANA.  Maybe we don't need to say anything at all and we find some way to steer implementations toward those ports.

Thanks to @costinm for the reminder.

**Comment by brianraymor** [comment]
@martinthomson - _maybe we don't need to say anything at all_ - could you clarify what you're proposing? Is this guidance that you want to capture in **Operational Considerations**?

**Comment by martinthomson** [comment]
I apologize for not taking the issue to the list; I intended to, but have been busy.

**Comment by costinm** [comment]
I think it's important to say something - port 443 is very unlikely to work
well. Any free port is good.

Under "operational considerations" we should mention that network
operators, router manufacturers, enterprises should
configure the defined port with a very long time to live in the NAT ( at
least 60 min ? ), and should not block it.
And for abuse control they may limit the number of connections allowed from
a single source IP  - I don't know how hard it is to
do with iptables.

**Comment by brianraymor** [comment]
Regarding time-to-live and NAT(s), [RFC5382 - NAT Behavioral Requirements for TCP
](https://tools.ietf.org/html/rfc5382#section-5) offers guidance:

REQ-5:  If a NAT cannot determine whether the endpoints of a TCP
      connection are active, it MAY abandon the session if it has been
      idle for some time.  In such cases, the value of the "established
      connection idle-timeout" MUST NOT be less than 2 hours 4 minutes.
      The value of the "transitory connection idle-timeout" MUST NOT be
      less than 4 minutes.
      a) The value of the NAT idle-timeouts MAY be configurable.

   Justification:  The intent of this requirement is to minimize the
      cases where a NAT abandons session state for a live connection.
      While some NATs may choose to abandon sessions reactively in
      response to new connection initiations (allowing idle connections
      to stay up indefinitely in the absence of new initiations), other
      NATs may choose to proactively reap idle sessions.  In cases where
      the NAT cannot actively determine if the connection is alive, this
      requirement ensures that applications can send keep-alive packets
      at the default rate (every 2 hours) such that the NAT can
      passively determine that the connection is alive.  The additional
      4 minutes allows time for in-flight packets to cross the NAT.

Also see [RFC6263](http://datatracker.ietf.org/doc/rfc6263/).

**Comment by brianraymor** [comment]
@martinthomson wrote _However, 5223 and 5228 are already registered with IANA_. Just to clarify for the broader audience, the ports are registered to hpvirtgrp and hpvroom, although unofficially used by APNS and GCM.

**Comment by coopdanger** [comment]
Unless I'm missing something, it seems like it would be better to register unallocated port numbers than squat on existing ones. There is enough new protocol here to justify registrations.

**Comment by costinm** [comment]
One the '2 hours and 4 min' - is there any mobile network that does that ?
In my experience 1 hour is the most you can hope for, 30 min is typical -
but many are way bellow.

Actually the most important thing is how they close the connection - I
believe the RFCs require sending
a RST packet to both ends, and many networks do this. However there are
cases where the connection
is silently closed, without any RST - and this causes the most pain.

On re-using 5228 or defining a new port - short term it will save work on
many operators if the port is reused,
but in time I assume the new port will end up getting set if enough
providers start using it.

**Comment by martinthomson** [comment]
Discussed in Prague; will confirm on list, but the plan is to request a port number, and then recommend that push services identify themselves as being available on port 443.  They can use alternative services to move traffic to the IANA allocated port number if that is possible.
