### ISSUE TITLE
Acknowledging Acknowledgements

### ISSUE THREAD

**Issue by brianraymor** [webpush-wg/webpush-protocol#39]
As [captured](https://www.ietf.org/proceedings/93/minutes/minutes-93-webpush) in the IETF 93 meeting minutes:

_Discussion about whether acknowledgement is needed for acknowledgement itself need to be discussed further. The feeling of the room was relatively strong inclination not to do this._

@dandruta did request support for the feature.

**Comment by martinthomson** [comment]
Discussed in Yokohama: close.
