### ISSUE TITLE
Delivery receipts

### ISSUE THREAD

**Issue by martinthomson** [webpush-wg/webpush-protocol#4]
This is likely straightforward, but it will require different amounts of machinery depending on the outcome of #3.  Application servers need to be told when their messages arrived.

The basic mechanism as described has the user agent send a conditional DELETE to the resource generated by each push message.  Tagging each message with an ETag would allow this to work without requiring too much extra state on the server (in essence, the ETag could carry that state).  The application server would get something like a push notification (hanging get, etc...) to inform it of delivery.

If we choose to disaggregate with #3, we should disaggregate here too.  Otherwise, we can just require that the application server register.

The disaggregation option has a small race condition that we would have to resolve if we were interested in efficiency for receipts, where the delivery receipt arrives at the resource while the hanging get from the application server hasn't yet made it to the server.  That could force the delivery receipts to be buffered in the same way that push messages are, which is definitely suboptimal.  In my opinion, we should treat all receipts as messages with TTL=0.

The aggregated solution might benefit from additional information being surfaced in the subscription, or maybe an application server could learn where to register for receipts when it pushes a message. The former increases the surface area of the API, the latter potentially adds some latency.

We could also resurrect 200/202 for direct delivery in addition to either of these options.  Note that the reasons for dropping 202 were largely driven by privacy needs that aren't valid in this context, so returning it should be OK.

**Comment by martinthomson** [comment]
This was addressed in #10.

**Comment by martinthomson** [comment]
I need to click the right link; this is clearly NOT resolved.

**Comment by brianraymor** [comment]
The associated pull request should also update **Implications for Application Reliability**.
