### ISSUE TITLE
Per-client subscription resource ('aggregated subscriptions')

### ISSUE THREAD

**Issue by brianraymor** [webpush-wg/webpush-protocol#41]
This feature has been requested multiple times - most [recently](https://mailarchive.ietf.org/arch/msg/webpush/HcTPdM5uv1HRnqldAOWTs8ClnTI) by @benbangert:

_I would propose allowing a Push Service to provide an authenticated client a single push subscription URL for all subscriptions for that client (the Location handed to App-Servers would of course vary for each subscription). The Push Promise path would then need to be the Location given out, so that the client could determine which subscription each message is for._

_This would allow for a single GET on connect, to begin receiving all notifications, for all subscriptions the client has setup previously. The client would need to realize that if it is already monitoring a subscription for notifications, and subscribes to another that has the same URL, then it should start expecting those notifications to be associated with the existing http2 stream._

_As this section currently stands, its quite a bit of data to resume subscription flow on a disconnect, which would be very expensive for mobile clients._

_Having a per-client subscription resource for all subscriptions would allow clients to resume notification flow faster on disconnect, with lower server resource overhead as the entire flow of notifications can resume on a reconnect without waiting for all the individual subscription GET's. It would also help avoid server overloading when large batches of clients come online/offline at once (1k clients at 80 subscriptions each connecting at once is a quick 80k hits, etc.)._

**Comment by ghost** [comment]
Since messages are individually addressable, would this require adding a special `Link` header (containing the subscription URL) to the pushed streams?

**Comment by brianraymor** [comment]
Proposal [shared](http://www.ietf.org/mail-archive/web/webpush/current/msg00272.html) on mailing list.

This is dependent on #44 for correlation.

**Comment by brianraymor** [comment]
Closed by #53
