### ISSUE TITLE
Returning data with Acknowledgements

### ISSUE THREAD

**Issue by brianraymor** [webpush-wg/webpush-protocol#42]
Extracted from #17 for separate discussion - @martinthomson wrote:

_MS have another state, where the app can send a negative signal indicating "yes, I received your message, but it caused an error". That might be a positive acknowledgment, but some applications want to have additional information carried back._

_Elio suggested that we might want to leave some latitude for the ~~push service~~ user agent to return ~~a range of status codes~~ opaque  data. Some suggestions might be sensible though._

**Comment by brianraymor** [comment]
As pointed out by Mark Nottingham, the title and description implied that this issue required a new range of HTTP status codes. Removing references to "status code" since the use of HTTP status codes was never intended.

**Comment by brianraymor** [comment]
Deferring until further data is available. If the proposal proceeds, there needs to be a length constraint on the opaque data.

**Comment by costinm** [comment]
I wouldn't mix 'sending messages from device to sender' with the ack. 
A payload in the ack would make it too close to an RPC or reverse HTTP, with the expectation that the request gets a matching ack with content. Which would be nice - but as a separate top level feature, in a future version.

To make things more complicated - the message may be sent to the UA and the UA may ack to the push service, but the app may not see the message until later ( at least on some battery-optimized devices ). Supporting an "ack after the app has seen the message' will be tricky and expensive in some cases.
