### ISSUE TITLE
Effect of h2 concurrent stream limit

### ISSUE THREAD

**Issue by martinthomson** [webpush-wg/webpush-protocol#43]
> >    A server that has a low concurrent stream limit can't be
> >     used with indepedent (i.e., not aggregated) subscriptions that exceed
> >     that number.  That might be all the incentive you need to encourage
> >     use of aggregation (in the other thread).  And I would not recommend
> >     opening a second connection to overcome this limit.
> 
> So in such a case, what is expected behavior when the concurrent stream limit is exceeded and a client wishes to make more subscriptions? The current WebPush spec has no language in it indicating what should occur, what action a client should take, etc. when it hits the max stream limit using independent subscriptions.

My suggestion would be to document the limit.  If a server wants to limit the concurrent streams in order to limit the number of concurrent, independent subscriptions, then that seems like a valid thing to do.  I would hope that clients respect this limit and therefore have to treat any additional subscriptions as failed (or at least temporarily inaccessible).

/cc @benbangert

**Comment by bbangert** [comment]
As a way to indicate the server is only interested in aggregate subscriptions, a concurrent setting of 2 might be one way to indicate this to the client. This would leave the client with a single 'command channel' to subscribe/unsubscribe, and the other for the notifications.

**Comment by ghost** [comment]
> This would leave the client with a single 'command channel' to subscribe/unsubscribe, and the other for the notifications.

Makes sense. This serializes message acks, too...but I'd hope a client never receives so many messages for that to be an issue.

**Comment by brianraymor** [comment]
Based on the discussions at IETF 93, there was a requirement captured in the [proposal](http://www.ietf.org/mail-archive/web/webpush/current/msg00272.html)

_The push service MAY return new subscription sets in response to different subscription requests from the same UA. This allows the push service to control the grouping._

If this requirement is retained, then SETTINGS_MAX_CONCURRENT_STREAMS could be set to the number of subscription sets + 1 for the stream to manage subscriptions ('command channel' above) for cases where a push service strictly enforces the use of subscription sets.

**Comment by bbangert** [comment]
This sounds good to me. If a client wants to poll notifications for multiple subscription sets, it could do the poll style query for each one in serial/parallel before issuing new commands. And then drop the connection. Either way I appreciate that the push server can exercise some resource limitations.

**Comment by brianraymor** [comment]
Closed by #53
