### ISSUE TITLE
Sender and client authentication 

### ISSUE THREAD

**Issue by costinm** [webpush-wg/webpush-protocol#44]
Push services may require authentication of UA, when they connect to the push service to subscribe or poll, and of application servers.

The spec should define one such mechanism - for example by using a key pair for each UA and for each application server, and using one of the common mechanisms - TLS client auth, JWT tokens - to authenticate.

Using a key pair also allows ApplicationServers to talk with multiple push services using a single identity. 

The key of the sender can be made available to the UA and webapplication by the push service - or can be used as an extra authentication in the encrypted content - for example signing the ephemeral key.

**Comment by martinthomson** [comment]
To register the idea that was floated today at our internal meeting...  Application servers could use a certificate.  There are already slots in certificates for the sort of information that a push service might like to use and an application might want to volunteer (email, URL, hostnames, etc...).  The setup process isn't exactly nice for certificates, but there are plenty of tools out there.

**Comment by costinm** [comment]
Sorry for the delay, too many things happening :-)

I think the important part is having the application servers use a key pair
- with one of the common mechanisms, either TLS client
  authentication or JWT tokens.

This will allow an app server to use the same key pair with multiple
webpush servers instead of having to register secrets with each
of them.

A certificate is not a bad idea - the main issue is who signs it, and
without having it signed/verified there is little value in having the
untrusted fields in a cert. I think it would be simpler to just generate
the key pair and send some contact info (email, hostname, etc) as a
'/register' request and avoid the certificate.  Other problems with
certificate: more wire overhead, and I'm not sure how it interacts with JWT
keys,
if that's one of the options. The email/URL/hostname only need to be sent
to the webpush provider once, the first time it is used.

One issue that was raised is the authentication of the sender by the
UA/receiving app - if the webpush service is not trusted.
Current proposal is to keep the public key secret - but if a sender is
using a key pair to authenticate with the push service, it can
also use it to sign something in the request - for example the ephemeral
key.

In either case - the sender will be identified by the public key, and will
authenticate using the private key - and same identity and
auth mechanism would work across multiple webpush provider.

Costin

**Comment by brianraymor** [comment]
Proposal shared on [mailing list](http://www.ietf.org/mail-archive/web/webpush/current/msg00411.html).

**Comment by brianraymor** [comment]
Addressed by the WG adoption of  [Voluntary Application Server Identification for Web Push ](https://datatracker.ietf.org/doc/draft-ietf-webpush-vapid/) as an optional feature.
