### ISSUE TITLE
Subscription identifier in push promises

### ISSUE THREAD

**Issue by martinthomson** [webpush-wg/webpush-protocol#46]
The subscriptions sets change causes the correlation between a push message resource and its subscription to come in the response.  Prior to that, the push promise included all the information necessary to identify the subscription.

This is a useful feature because it allows a push service and user agent to support w3c/push-api#168 without anything special: all the server needs to do is send all the push promises it knows about before it starts pushing responses.  That way, the user agent will know about how many push messages are arriving for a given application before it dispatching an event to an application.

We should recommend that the Link header field be included in the push promise (i.e., the promised request).

**Comment by brianraymor** [comment]
Closed by #53
