### ISSUE TITLE
Message encryption

### ISSUE THREAD

**Issue by martinthomson** [webpush-wg/webpush-protocol#5]
The sense I got from the meeting was that the text in webpush-encryption was probably best merged into the main draft.

**Comment by brianraymor** [comment]
I reviewed the audio from the webpush meeting - especially comments from Mike and Joe. My sense is that it's premature to merge and requires more discussion on the list. Reviewing the httpbis etherpad for the draft-nottingham-http-encryption-encoding discussion, it appeared that Paul Hoffman (?) suggested alternatives:

_ph: why wont CMS w/smime eg smiime 3 not work?_
_pls engage smime list_

_mnot: so this spec is an fyi at this point_

**Comment by martinthomson** [comment]
Let's just treat this as a issue tracking the encryption thing.

**Comment by brianraymor** [comment]
This has been accepted as a work item in webpush. Closing.
