### ISSUE TITLE
Redirect from subscription to containing set

### ISSUE THREAD

**Issue by martinthomson** [webpush-wg/webpush-protocol#55]
This allows a push service to store nothing for a subscription and hold everything in the set if it likes.  I think that we discussed allowing this in Prague.

**Comment by brianraymor** [comment]
If the Push Service supports subscription sets and the User Agent attempts to request messages from a specific push subscription rather than the subscription set, then the Push Service MAY return a 307 with the Location set to the push:set URL?

**Comment by martinthomson** [comment]
Not clear, I have an email now saying that we'd discussed the issue and didn't need a redirect.  Not having one is certainly much nicer.  If we can get away with it.

cc @bbangert

**Comment by bbangert** [comment]
I'm fine not requiring it, which would allow a knowledgeable client to group subscriptions as it sees fit. However, a buggy client would end up only getting notifications for a single set, and lots of 503's (which should let the author figure out their bug quickly).

**Comment by brianraymor** [comment]
@martinthomson and @bbangert - If you're still cool with not requiring this change, then I'll close the issue.

**Comment by martinthomson** [comment]
Close it.

**Comment by bbangert** [comment]
I'm good.
