### ISSUE TITLE
Examples are invalid

### ISSUE THREAD

**Issue by bbangert** [webpush-wg/webpush-protocol#74]
All of the examples of Push messages show plain-text content of some sort with:

```
   Content-Type: text/plain;charset=utf8
```

However, under WebPush, all payload content must be encrypted, and include crypto headers (which the examples don't include as well). Section 9.1 indicates that encryption is required without linking to the specification documenting it.

Is there some utility in documenting invalid examples given the headers necessary for encrypted payloads?

**Comment by brianraymor** [comment]
I'd note that the 9.1 requirement is referring to the Web Push API not the protocol itself:

_The Web Push API codifies this practice by requiring that each push subscription created by the browser be bound to a browser generated encryption key._

Encryption is an optional feature which is one reason that the related draft is separate from the core protocol.

**Comment by bbangert** [comment]
That sounds reasonable, does this mean there's some intention to create a "Web Push API" specification that is referred to here? I can only find the "Message Encryption for Web Push" spec which covers it.

I'll admit I am somewhat sad that one of the top search results for 'web push' will lead a developer to think unencrypted plain-text payloads are acceptable, but I understand the desire to keep these specs separate.

**Comment by brianraymor** [comment]
That would be the W3C API - https://w3c.github.io/push-api/

**Comment by bbangert** [comment]
Ah, I've never heard it referred to as the Web Push API. Could a reference be stuck in with a footnote so that's clear?

Closing this as the lack of crypto is intentional.
