### ISSUE TITLE
Clarify that a POST request is needed for requesting push message delivery

### ISSUE THREAD

**Issue by marco-c** [webpush-wg/webpush-protocol#79]
In other sections (e.g. [Subscribing for Push Messages](https://tools.ietf.org/html/draft-ietf-webpush-protocol-03#section-4)), it's clear that a POST request is required. In this section instead, you can only infer it from the example, but you could think that other methods are supported as well (e.g. I was starting to think PUT was allowed).

**Comment by brianraymor** [comment]
Update Section 6 to:
   An application server requests the delivery of a push message by
   sending a HTTP **POST** request to a push resource distributed to the
   application server by a user agent.

**Comment by brianraymor** [comment]
Resolved in -04.
