### ISSUE TITLE
How does the application server decide that two push resources are the "same"

### ISSUE THREAD

**Issue by martinthomson** [webpush-wg/webpush-protocol#85]
In #84, @brianraymor notes that the creation of a subscription - either by the user agent or application server - should be rejected if the secondary information is invalid.

I think that for a user agent, this is fine.  They only talk to a single push service.  However, for the receipt subscription there is a potential hazard.  In that direction, the application server has no overt knowledge about the relationship between two push resources.  That means that it is left to guess which are the same and which are different.

Are `https://a.service.example/blah` and `https://b.service.example/blargh` the same?  Would it be reasonable to expect that I can take the receipt subscription returned from the former and pass it to the latter?

I think that we need a simple rule here: if the origin (scheme, host, port) is the same, then the application server SHOULD attempt to reuse the receipt subscription.  That makes the choice in #84 correct and safe.  It makes the example deployment above more difficult, but I don't think that we have anyone doing this (/cc @bbangert for comment here).  If a server cannot validate that a receipt subscription that it provided itself, then we have a big issue.

This also avoids the implication from the proposed text that says that a receipt subscription obtained from `https://example.com/o` has to be validated somehow when passed to `https://bar.example/t`.

**Comment by bbangert** [comment]
> Are https://a.service.example/blah and https://b.service.example/blargh the same? Would it be reasonable to expect that I can take the receipt subscription returned from the former and pass it to the latter?

Agreed, these are not the same. If the receipt resource is relative as shown in the PR, then I'd expect it to be relative to the scheme, host, and port matching.

**Comment by brianraymor** [comment]
How about:
_         For future receipt requests to the same origin <xref target="RFC6454"/>, 
          the application server SHOULD include the returned receipt subscription to
          allow the push service to aggregate receipts. The push service SHOULD return
          the same receipt subscription in its response, although it MAY return a new
          receipt subscription if it is unable to reuse the one provided by the application server._

**Comment by martinthomson** [comment]
WFM

**Comment by brianraymor** [comment]
Closed by #84
