### ISSUE TITLE
Clarify application servers removing subscriptions in section 7.3

### ISSUE THREAD

**Issue by ghost** [webpush-wg/webpush-protocol#86]
https://tools.ietf.org/html/draft-ietf-webpush-protocol-00#section-7.3 says this:

> A user agent or application server can request that a subscription be
> removed by sending a DELETE request to the push message subscription
> or receipt subscription URI.

It's clear that a user agent can unsubscribe by deleting its subscription resource. However, it's not obvious to me how the app server can do this, since it doesn't have access to the subscription resource.

I'm wondering if the last part of that sentence should read "push message subscription resource or push resource URI". In other words, the following example URIs would be equivalent:

```
DELETE /s/LBhhw0OohO-Wl4Oi971UGsB7sdQGUibx
DELETE /p/JzLQ3raZJfFBR0aqvOMsLrt54w4rJUsV
```

What do you think?

**Comment by martinthomson** [comment]
I don't think that this is a good idea.  An application server isn't necessarily the sole owner of a push resource, and if it thinks that it is, then it's easy enough for it to stop using the push resource.

**Comment by brianraymor** [comment]
The application server has access to a receipt subscription URI for receiving acknowledgements. For clarity, this should be separated out into two statements - one for UA (message subscription resource) and one for AS (receipt subscription resource).

**Comment by martinthomson** [comment]
I think that it's perfectly reasonable for an application server to delete a receipt subscription.  Kit seems to be asking for the ability to delete a push subscription.

**Comment by brianraymor** [comment]
@kitcambridge - the push message subscription and the push resource are not equivalent. Earlier we modeled them as separate capabilities - the push message subscription is for reading/deleting and the push resource is for writing. 

There is no specific guidance about an AS deleting a push resource. Do we need to address this by having the PS return a 400 (Bad Request)? As Martin noted, the AS could simply stop using the push resource. No scenario for deleting it.

**Comment by ghost** [comment]
Oh, I see. I misread the quoted sentence as "it's possible for a UA or an AS to delete a push subscription," and I filed this issue because I didn't see a way for the AS to do that. In fact, the sentence is saying two separate things:
- A UA can delete a push subscription.
- An AS can delete a receipt subscription.

Thanks!
