### ISSUE TITLE
Flow Control for Application Server Receipts

### ISSUE THREAD

**Issue by brianraymor** [webpush-wg/webpush-protocol#87]
Conversation starts [here](http://www.ietf.org/mail-archive/web/webpush/current/msg00504.html):

_How does the PS know that AS can accept more receipts, and how does it know a receipt has been accepted by the AS ?_

**Comment by RichardMaher** [comment]
Two-Pipe model a la mode de TIP?
https://tools.ietf.org/html/rfc2372

**Comment by RichardMaher** [comment]
@brianraymor 

WRT https://mailarchive.ietf.org/arch/attach/webpush/pdf_mlRKG.pdf ("5.4. Updating Push Messages" and the sheer nonsense of 4.1)

Can you please ask your Microsoft colleagues to explain what Topic messages are for: -
https://blogs.windows.com/buildingapps/2013/09/16/delivering-push-notifications-to-millions-of-devices-with-windows-azure-notification-hubs/

Topic-based multicast. Broadcasting push notifications to different markets, based on interests of individual users, requires efficient pub sub routing and topic-based multicast logic

***TOPICS are NOT collapse keys!***

**Comment by brianraymor** [comment]
@martinthomson started [flow control for server push discussion](https://lists.w3.org/Archives/Public/ietf-http-wg/2016AprJun/0197.html) on HTTPbis

**Comment by brianraymor** [comment]
Costin [wrote](http://www.ietf.org/mail-archive/web/webpush/current/msg00530.html):
_we discussed my concerns on flow control for push promises, and I think it's reasonable to have them addressed either as part of http2 or as a separate document._ 

I'm closing this issue for webpush since it's no longer actionable - @costinm - re-open if you want to track for "futures". I'll tag appropriately.
