### ISSUE TITLE
Message collapsing

### ISSUE THREAD

**Issue by martinthomson** [webpush-wg/webpush-protocol#9]
Need to do this once we have #3 and #6 are sorted out.

**Comment by brianraymor** [comment]
If we decide to pursue - To keep related changes together, the pull request should include the changes for the **conditional** DELETE of the message resource by the user agent.

**Comment by martinthomson** [comment]
Defer to -01.

**Comment by martinthomson** [comment]
Defer again.

**Comment by brianraymor** [comment]
Deferred multiple times. Closing. Can be reopened if there is a requirement to support this scenario.

**Comment by martinthomson** [comment]
Discussed in Yokohama: action on @martinthomson to generate a pull request that uses a string collapse key.  That would allow the application server to operate in a stateless mode, something that the previous pull request would not allow.

**Comment by martinthomson** [comment]
Just did a scan of the header fields that are already registered.  The only one that is even a remote possibility for this purpose is [SLUG](https://tools.ietf.org/html/rfc5023#section-9.7).  It looks like we might want to ask for another new one, current candidate: `Topic`.

**Comment by brianraymor** [comment]
_Topic_ sounds like a better option than reuse in this case.

**Comment by costinm** [comment]
"Topic" may be a bit confusing, it is commonly used in pubsub. I don't know if pubsub uses a Topic header, but it may still confuse developers.

**Comment by RichardMaher** [comment]
So this is where it all went wrong :-( 

https://github.com/webpush-wg/webpush-protocol/issues/87

**_TOPICS are NOT collapse keys!**_
